# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-sns-cloudwatch-sns-alarms
  description: Terraform module that configures CloudWatch SNS alerts for SNS
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-module, aws, sns, aws-sns, cloudwatch, sns-alerts
